name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: webhook.rb
  DOCKER_TARGET_PLATFORM: linux/arm/v7

jobs:

  docker-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up QEMU
      # uses: docker/setup-qemu-action@v1
    - name: Create builders
      run: docker buildx create --name mybuilder --use
    - name: Check builders
      run: docker buildx ls
    - name: Buildx image
      run: docker buildx build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --platform linux/arm64,linux/arm/v7
    - name: List images
      run: docker images
    - name: Log in to registry
      # This is where you will update the personal access token to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/veverkap/webhook.rb
        echo IMAGE_ID=$IMAGE_ID
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
