name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

env:
  IMAGE_NAME: webhook.rb
  DOCKER_TARGET_PLATFORM: linux/arm/v7

jobs:

  docker-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create builders
      run: docker buildx create --name mybuilder --use
    - name: Check builders
      run: docker buildx ls
    - name: Inspect builders
      run: docker buildx inspect --bootstrap
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          webhook.rb
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
    # - name: Buildx linux/amd64
    #   run: docker buildx build --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --platform linux/amd64 --output type=docker .
    # - name: Buildx linux/arm64
    #   run: docker buildx build --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --platform linux/arm64 --output type=docker .
    # - name: Buildx linux/arm/v7
    #   run: docker buildx build --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --platform linux/arm/v7 --output type=docker .
    # - name: List images
    #   run: docker images
    # - name: Push image
    #   run: |
    #     IMAGE_ID=ghcr.io/veverkap/webhook.rb
    #     echo IMAGE_ID=$IMAGE_ID
    #     docker tag $IMAGE_NAME $IMAGE_ID:latest
    #     docker push $IMAGE_ID:latest
